package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;

public class LitemallPushGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.member_count
     *
     * @mbg.generated
     */
    private Integer memberCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.user_ids
     *
     * @mbg.generated
     */
    private String userIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.last_updated
     *
     * @mbg.generated
     */
    private LocalDateTime lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_group.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @mbg.generated
     */
    public Integer getMemberCount() {
        return memberCount;
    }

    /**
     * @mbg.generated
     */
    public void setMemberCount(Integer memberCount) {
        this.memberCount = memberCount;
    }

    /**
     * @mbg.generated
     */
    public String getUserIds() {
        return userIds;
    }

    /**
     * @mbg.generated
     */
    public void setUserIds(String userIds) {
        this.userIds = userIds;
    }

    /**
     * @mbg.generated
     */
    public LocalDateTime getLastUpdated() {
        return lastUpdated;
    }

    /**
     * @mbg.generated
     */
    public void setLastUpdated(LocalDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
