package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;

public class LitemallPushLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.push_type
     *
     * @mbg.generated
     */
    private String pushType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.content
     *
     * @mbg.generated
     */
    private String content;

    private String contentType;

    private String mediaId;

    private String page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.target_type
     *
     * @mbg.generated
     */
    private String targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.target_group_id
     *
     * @mbg.generated
     */
    private Integer targetGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.target_tag_id
     *
     * @mbg.generated
     */
    private String targetTagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.total_count
     *
     * @mbg.generated
     */
    private Integer totalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.success_count
     *
     * @mbg.generated
     */
    private Integer successCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.fail_count
     *
     * @mbg.generated
     */
    private Integer failCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.scheduled_at
     *
     * @mbg.generated
     */
    private LocalDateTime scheduledAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.sent_at
     *
     * @mbg.generated
     */
    private LocalDateTime sentAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.error_msg
     *
     * @mbg.generated
     */
    private String errorMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_push_log.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @mbg.generated
     */
    public String getPushType() {
        return pushType;
    }

    /**
     * @mbg.generated
     */
    public void setPushType(String pushType) {
        this.pushType = pushType;
    }

    /**
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getMediaId() {
        return mediaId;
    }

    public void setMediaId(String mediaId) {
        this.mediaId = mediaId;
    }

    public String getPage() {
        return page;
    }

    public void setPage(String page) {
        this.page = page;
    }

    /**
     * @mbg.generated
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * @mbg.generated
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }

    /**
     * @mbg.generated
     */
    public Integer getTargetGroupId() {
        return targetGroupId;
    }

    /**
     * @mbg.generated
     */
    public void setTargetGroupId(Integer targetGroupId) {
        this.targetGroupId = targetGroupId;
    }

    /**
     * @mbg.generated
     */
    public String getTargetTagId() {
        return targetTagId;
    }

    /**
     * @mbg.generated
     */
    public void setTargetTagId(String targetTagId) {
        this.targetTagId = targetTagId;
    }

    /**
     * @mbg.generated
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * @mbg.generated
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * @mbg.generated
     */
    public Integer getSuccessCount() {
        return successCount;
    }

    /**
     * @mbg.generated
     */
    public void setSuccessCount(Integer successCount) {
        this.successCount = successCount;
    }

    /**
     * @mbg.generated
     */
    public Integer getFailCount() {
        return failCount;
    }

    /**
     * @mbg.generated
     */
    public void setFailCount(Integer failCount) {
        this.failCount = failCount;
    }

    /**
     * @mbg.generated
     */
    public LocalDateTime getScheduledAt() {
        return scheduledAt;
    }

    /**
     * @mbg.generated
     */
    public void setScheduledAt(LocalDateTime scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    /**
     * @mbg.generated
     */
    public LocalDateTime getSentAt() {
        return sentAt;
    }

    /**
     * @mbg.generated
     */
    public void setSentAt(LocalDateTime sentAt) {
        this.sentAt = sentAt;
    }

    /**
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * @mbg.generated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * @mbg.generated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }

    /**
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}
